googleAnalytics = "G-Z5VF0FL7ED"
# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work

# Setup
baseURL = "https://partigabor.github.io/spice/"
title = "Spices & Spice Terminology Database 1.0 (Beta)"
languageCode = "en-us"
defaultContentLanguage = 'en'
theme = ["hugo-book"]

# copyright = 'Copyright' #?

# The folder where Hugo builds the website and Github reads it from
publishDir = "docs"

# Assets folder
assetDir = "assets"

# Warning: Images are read from the static/images folder of the main website: https://partigabor.github.io/
# Exception is for figures used by gallery shortcode.

# Fix urls so Hugo can find images on this website.
# WARNING! Kills Search function if true
# canonifyurls=true 

# # (Optional) If you provide a Disqus shortname, comments will be enabled on
# # all pages.
# disqusShortname = "my-site"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# Emojis
enableEmoji = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
# disableKinds = ['taxonomy', 'taxonomyTerm']



# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = "English ðŸ‡¬ðŸ‡§"
  contentDir = 'content'
  weight = 1
  [languages.en.params]
      fontheading = "Raleway"
      fontbody = "Raleway"

[languages.hu]
  languageName = "Hungarian ðŸ‡­ðŸ‡º"
  contentDir = 'content.hu'
  weight = 2
  title = 'FÅ±szer Ã©s fÅ±szernÃ©v adatbÃ¡zis'

# [languages.ar]
#   languageName = "Arabic ðŸ‡µðŸ‡¸"
#   contentDir = 'content.ar'
#   weight = 3
#   title = 'Ù‚Ø§Ø¹Ø¯Ø© Ø¨ÙŠØ§Ù†Ø§Øª Ù…ØµØ·Ù„Ø­Ø§Øª Ø§Ù„ØªÙˆØ§Ø¨Ù„ ÙˆØ§Ù„Ø¨Ù‡Ø§Ø±Ø§Øª'
#   languagedirection = 'rtl'
#   [languages.ar.params]
#     fontheading = "Noto+Naskh+Arabic"
#     fontbody = "Noto+Naskh+Arabic"

# [languages.zh]
#   languageName = "Chinese ðŸ‡­ðŸ‡°"
#   contentDir = 'content.zh'
#   weight = 4
#   title = 'é¦™æ–™å’Œé¦™æ–™è¡“èªžæ•¸æ“šåº«'
#   [languages.zh.params]
#     fontheading = "Noto+Serif+TC"
#     fontbody = "Noto+Serif+TC"

# # Supposed to skip a language for dev
# disableLanguages = ['hu']

[menu]
# [[menu.before]]

# [[menu.after]]
#   name = "Creator"
#   url = "https://partigabor.github.io/"
#   weight = 20

# [[menu.after]]
#   name = "GitHub"
#   url = "https://github.com/partigabor"
#   weight = 20

[params]
  fontheading = "Brill"
  fontbody = "Brill"


  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'images/polyu-logo.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = '/menu'

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = 'book'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/partigabor/spice'

  # (Optional, default 'commit') Specifies commit portion of the link to the page's last modified
  # commit hash for 'doc' page type.
  # Requires 'BookRepo' param.
  # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
  # Github uses 'commit', Bitbucket uses 'commits'
  BookCommitPath = 'commit'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Edit path must point to root directory of repo.
  # BookEditPath = 'edit/main/exampleSite'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'January 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  BookServiceWorker = false

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  BookTranslatedOnly = false

  # custom_css = ["css/custom_style.css"]  #under [params]

  favicon = "/images/favicon.ico"  

  # manually added
[params.mysite]
  # footer
  websiteterms = "https://partigabor.github.io/spice/meta/terms"
  privacypolicy = "https://partigabor.github.io/spice/meta/privacy"
  contact = "https://partigabor.github.io/spice/meta/contact"
  author = "GÃ¡bor Parti"
  copystart = "2020" 

  # hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

###############

# https://web.archive.org/web/20170310005739/https://stoned.io/web-development/hugo/How-To-Dynamically-Use-Google-Fonts-In-A-Hugo-Website/

# https://github.com/alex-shpak/hugo-book